#Siga21SociosBundle_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: Siga21SociosBundle:Default:index }


Siga21SociosBundle_homepage:
    pattern:  /mano/
    defaults: { _controller: Siga21SociosBundle:Mano:index}

_mano:
    resource: ./routing/mano.yml


