# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


#-----------ocaso bundle, o noso bundle ---------------
OcasoOcasoBundle:
    resource: "@OcasoOcasoBundle/Resources/config/routing.yml"
    prefix:   /
    
Siga21SociosBundle:
        resource: "@Siga21SociosBundle/Resources/config/routing.yml"
        prefix:   /
    



