parameters:
#    siga21_articulos.example.class: Siga21\ArticulosBundle\Example

services:
#    siga21_articulos.example:
#        class: %siga21_articulos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
