parameters:
#    siga21_tareas.example.class: Siga21\TareasBundle\Example

services:
#    siga21_tareas.example:
#        class: %siga21_tareas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
