<?php

namespace Siga21\FamiliaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubfamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubfamiliaRepository extends EntityRepository
{
}