Ocaso_principal:
    pattern:  /ocaso/{name}
    defaults: { _controller: OcasoOcasoBundle:Default:index }

Ocaso_adios:
    pattern:  /cenit/{name}
    defaults: { _controller: OcasoOcasoBundle:Default:ciao }

Ocaso_dos:
    pattern:  /controlador2/
    defaults: { _controller: OcasoOcasoBundle:Secondo:index }

Ocaso_tres:
    pattern:  /controlador3/
    defaults: { _controller: OcasoOcasoBundle:Secondo:acona }

