parameters:
#    ocaso_ocaso.example.class: Ocaso\OcasoBundle\Example

services:
#    ocaso_ocaso.example:
#        class: %ocaso_ocaso.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
