<?php

namespace Siga21\ArticulosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticulosRepository extends EntityRepository
{
}