parameters:
#    siga21_familia.example.class: Siga21\FamiliaBundle\Example

services:
#    siga21_familia.example:
#        class: %siga21_familia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
